#!/bin/bash

# Use . to add all or supply filename or directory to select what to add
read -r -p 'Adding: ' toAdd

# Supply your commit message
read -r -p 'Commit message: ' desc

# Supply branch your using
read -r -p 'Branch: ' branch

git add $toAdd
git add -u
git commit -m "$desc"
git push origin $branch
